routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/* use App\Post;
use App\User;
use App\Country;

use App\Photo;
use App\Tag;
use App\Video; */

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/posts', 'PostsController');

//he comentado las siguientes rutas ya que son del primer proyecto y estas mismas no se usarán.
/* 
    //Ruta para la inserción de datos quemados a la db
    Route::get('/post/insert', function () {
        $result = DB::insert('INSERT INTO posts(title, content) 
                            VALUES(?,?)', 
                            array('Training laravel', 'This is the training'));
        return $result;
    });
    //Ruta para la edición de datos quemados a la db
    Route::get('/post/update', function () {
        $result = DB::update('UPDATE posts 
                            SET title = "Update title" 
                            WHERE id = ?', 
                            array(2));
        return $result;
    }); 
    //Ruta para el listado de registros
    Route::get('/post', function () {
        $result = DB::select('SELECT title, content
                            FROM posts');
        return count($result) ? $result : 'Without data';
    });
    //Ruta para la eliminación de registros
    Route::get('/post/delete', function () {
        $result = DB::delete('DELETE FROM posts 
                            WHERE id=?', 
                            array(1));
        return $result;
    });
    // ----------------------------------------------
    //Rutas para consultas eloquent
    // ----------------------------------------------
    //Mostrar todos los registros de la db
    Route::get('/eloquent', function() {
        $eloquentRes = Post::all(); 
        foreach($eloquentRes as $post){
            echo 'Id: ' . $post->id .', Title: ' . $post->title . ', Content: '. $post->content . '<br>';
        };
    });
    //Insertar nuevo registro
    Route::get('/eloquent/insert', function() {
        $post = new Post; 
        $post->title    = "Eloquent insert";
        $post->content  = "This is new content";
        $post->save();
    });
    //Insertar nuevo registro
    Route::get('/eloquent/create', function() { 
        Post::create(array('title' => 'eloquent create', 'content' => 'Content created'));
    });
    //Actualizar registro
    Route::get('/eloquent/update', function() {
        $post =  Post::find(2); 
        $post->title    = "Eloquent update";
        $post->content  = "Content updated";
        $post->save();
    });
    //Eliminar registro
    Route::get('/eloquent/delete', function() {
        Post::find(2)->delete();   
    });
    //Destruir registro
    Route::get('/eloquent/destroy', function() {
        //se puede destruir 1 o varios
        //Post::destroy(3);   
        Post::destroy(array(4, 5));   
    });
    //Eliminar registro con softDelete
    Route::get('/eloquent/softDelete/delete', function() {
        Post::find(6)->delete();   
    });
    //Buscar registros por medio de id que fueron eliminados por softdelete
    Route::get('/eloquent/softDelete/find', function() {
        return Post::withTrashed()->where('id', 6)->get();   
    }); 
    Route::get('/eloquent/softDelete', function() {
        return Post::onlyTrashed(6)->get();   
    });
    //restaurar registros eliminados por medio de softdelete
    Route::get('/eloquent/softDelete/restore', function() {
        return Post::withTrashed()->where('id', 6)->restore();   
    });
    //Forzar eliminación
    Route::get('/eloquent/softDelete/forceDelete', function() {
        return Post::withTrashed()->where('id', 7)->forceDelete();   
    });

    //  ----------------------------
    // Mostrando relaciones
    // -----------------------------

    // Mostrar el post del user
    Route::get('/relation/user/{id}/post', function($id){
        return User::find($id)->post;
    });
    // Mostrar el user del post
    Route::get('/relation/post/{id}/user', function($id){
        return Post::find($id)->user;
    });

    // Mostrar los post de un user
    Route::get('/relation/user/{id}/posts', function($id){
        $user = User::find($id);
        foreach ($user->posts as $post) {
            echo $post . '<br>';
        }
    }); 

    // Mostrar roles de un usuario
    Route::get('/relation/user/{id}/roles', function($id){
        $user = User::find($id);
        foreach ($user->roles as $role) {
            echo $role ;
        }

        //también podemos usarel siguiente porcedimiento más detallado
        // $user = User::find($id)->roles()->orderBy('id', 'desc')->get();
        // return $user;
    });

    // Mostrar datos de la table intermedia entre rol y usuario
    Route::get('/relation/pivot/user/{id}/roles', function($id){
        $user = User::find($id);
        foreach ($user->roles_pivot as $role) {
            echo $role->pivot->created_at . '<br>';
        } 
    });

    //Mostrar pais de una publicación
    Route::get('relation/user/country', function(){
        $country = Country::find(1);
        foreach ($country->posts as $post) {
            echo $post->title . '<br>';
        }
    });


    // -----------------------
    // version 2 
    // ------------------------

    //Relación polimorfica user photo
    Route::get('relation/polymorph/user', function(){
        $user = User::find(1);

        foreach ($user->photos as $photo) {
        echo $photo . '<br>';
        }
    });

    //Relación polimorfica post photo
    Route::get('relation/polymorph/post', function(){
        $post = Post::find(1);

        foreach ($post->photos as $photo) {
        echo $photo . '<br>';
        }
    });

    //relacion polimorfica photo (user, post)
    Route::get('relation/polymorph/photo/{id}', function($id){
        $photo = Photo::findOrFail($id); 
        return $photo->imageable;
    });

    //relacion polimorfica muchos a muchos post tag
    Route::get('relation/polymorph/post/tag', function(){
        $post = Post::find(1); 
        foreach ($post->tags as $tag) {
            echo $tag . '<br>';
        }
    });

    //relacion polimorfica muchos a muchos tag post
    Route::get('relation/polymorph/tag/post', function(){
        $tag = Tag::find(2); 
        foreach ($tag->posts as $post) {
            echo $post . '<br>';
        }
    });

    //relacion polimorfica muchos a muchos post tag
    Route::get('relation/polymorph/video/tag', function(){
        $video = Video::find(1); 
        foreach ($video->tags as $tag) {
            echo $tag . '<br>';
        }
    });

    //relacion polimorfica muchos a muchos tag video
    Route::get('relation/polymorph/tag/video', function(){
        $tag = Tag::find(1); 
        foreach ($tag->video as $post) {
            echo $post . '<br>';
        }
    });
    
    // -----------------------
    // 
    // ------------------------ 
*/

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Softdeletes;
class Post extends Model
{
    //variable para caber el directorio de las imagenes
    public $directory = "/images/";
    //propiedad para eliminacion por softdelete
    use Softdeletes;
    protected $dates = ['deleted_at'];

    //Propiedades del modelo Post
    protected $fillable = [
        'title',
        'content',
        'path'
    ];
      //función para mostrar los registros relacionas de un post en usuario
    public function user(){  
        return $this->belongsTo('App\User');
    } 
    //--------------------
    //version 2
    //-------------------
    //ralacion polimofica con photo
    public function photos(){
        return $this->morphMany('App\Photo', 'imageable');
    }
    //relacion polimorfismo muchos a muchos
    public function tags(){
        return $this->morphToMany('App\Tag', 'taggable');
    }
    //accesor mutatr para el path de las imagenes
    public function getPathAttribute($value){
        return $this->directory . $value;
    }

}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePostRequest;
use App\Post;
use Illuminate\Http\Request;

class PostsController extends Controller
{ 
    public function index()
    {
        $posts = Post::all();
        return view('post.index', compact('posts'));
    } 
    public function create()
    { 
        return view('post.create');
    } 
    public function store(CreatePostRequest $request)
    { 
        $input = $request->all();
        if($file = $request->file('file')){
            $name = $file->getClientOriginalName();
            $file->move('images', $name);
            $input['path'] = $name;

        } 
        Post::create($input);
        return redirect('posts');
    } 
    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view('post.show', compact('post'));
    } 
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('post.edit', compact('post'));
    } 
    public function update(CreatePostRequest $request, $id)
    { 
        Post::findOrFail($id)->update($request->all());
        return redirect('posts');
    } 
    public function destroy($id)
    {
        Post::findOrFail($id)->delete();
        return redirect('posts');
    }
}

resources/views/post/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Publiciones</title>
</head>
<body> 
    {!! Form::open(['method' => 'POST', 'action' => 'PostsController@store', 'files' => true]) !!} 
        {{ csrf_field() }} 
        <div class="form-group">
            {!! Form::label('Archivo', 'Archivo') !!}
            {!! Form::file('file', ['class' => 'form-control']) !!}
        </div>  

        <div class="form-group">
            {!! Form::label('Titulo', 'Titulo') !!}
            {!! Form::text('title', null, ['class' => 'form-control']) !!}
        </div>  
        <div class="form-group">
            {!! Form::label('Contenido', 'Contenido') !!}
            {!! Form::text('content', null, ['class' => 'form-control']) !!}
        </div>   
        {!! Form::submit('Guardar', ['class' => 'form-control']) !!}
    {!! Form::close() !!} 

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>
                    {{$error}}
                </li>
            @endforeach    
        </div> 
    @endif
</body>
</html>

resources/views/post/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Publicación</title>
</head>
<body> 
    {!! Form::model($post, ['method' => 'PATCH', 'action' => ['PostsController@update', $post->id]]) !!} 
        {{ csrf_field() }} 
        <div class="form-group">
            {!! Form::label('Titulo', 'Titulo') !!}
            {!! Form::text('title', null, ['class' => 'form-control']) !!}
        </div>  
        <div class="form-group">
            {!! Form::label('Contenido', 'Contenido') !!}
            {!! Form::text('content', null, ['class' => 'form-control']) !!}
        </div>   
        {!! Form::submit('Actualizar', ['class' => 'form-control']) !!}
    {!! Form::close() !!} 
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>
                    {{$error}}
                </li>
            @endforeach    
        </div> 
    @endif
</body>
</html>

resources/views/post/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Publicaciones</title>
</head>
<body> 
    <h1>Publicaciones</h1>  
    <a href="{{route('posts.create')}}">Nuevo</a>
    <table>
        <thead>
            <tr>
                <th>
                    Titulo
                </th>
                <th>
                    Contenido
                </th>
                <th>
                    Imagen
                </th>
                <th>
                    Opciones
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach ($posts as $post)  
                <tr>
                    <td>
                         {{$post->title}}
                    </td>
                    <td>
                        {{$post->content}}
                    </td>
                    <td>
                        <div class="container">
                            <img height="100" src="{{$post->path}}" alt=""> 
                        </div> 
                    </td>
                    <td>
                        <a href="{{route('posts.show', $post->id)}}"> Detalles</a>
                        <a href="{{route('posts.edit', $post->id)}}"> Editar</a>  
                        {!! Form::open(['method' => 'DELETE', 'action' => ['PostsController@destroy', $post->id]]) !!} 
                        {{ csrf_field() }}   
                        {!! Form::submit('Eliminar', ['class' => 'form-control']) !!}
                    {!! Form::close() !!} 
                    </td>
                </tr> 
            @endforeach
        </tbody>
    </table>
    
</body>
</html>

resources/views/post/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Post</title>
</head>
<body>
    <h1>Detalles</h1>
    <ul>
        <li>{{$post->title}}</li>
        <li>{{$post->content}}</li>
    </ul>
    <a href="{{route('posts.edit', $post->id)}}">Editar</a>
</body>
</html>